addSbtPlugin("org.scalameta"  % "sbt-scalafmt"    % "2.5.2")
addSbtPlugin("com.lucidchart" % "sbt-cross"       % "4.0")
addSbtPlugin("com.github.sbt" % "sbt-release"     % "1.4.0")
addSbtPlugin("org.scala-sbt"  % "sbt-autoversion" % "1.0.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"    % "3.12.2")
addSbtPlugin("com.github.sbt" % "sbt-pgp"         % "2.2.1")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"   % "0.13.1")
addSbtPlugin("org.scalaxb"    % "sbt-scalaxb"     % "1.12.1")
